import Head from "next/head";
import Link from "next/link";
import Dashboard from "~/components/Dashboard";
import Init from "~/components/Init";
import Routeservice from "~/components/Routeservice";

import { api } from "~/utils/api";

export default function Home() {
  const config = api.config.getLatest.useQuery();

  if (!config.data) {
    return <Init></Init>;
  } else {
    console.log(config.data);
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <Dashboard />
        </main>
      </>
    );
  }
}
